default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-50-16-229-91.compute-1.amazonaws.com
  pool: 5
  database: dactfsmgpbtmge
  username: tsowomyqcjnhqg
  password:  tu61zm6Q-e_ZOVS7kQ7ZsM5m4W

development:
  adapter: postgresql
  encoding: unicode
  host: ec2-50-16-229-91.compute-1.amazonaws.com
  pool: 5
  database: dactfsmgpbtmge
  username: tsowomyqcjnhqg
  password:  tu61zm6Q-e_ZOVS7kQ7ZsM5m4W

staging:
  adapter: postgresql
  encoding: unicode
  host: ec2-50-16-229-91.compute-1.amazonaws.com
  pool: 5
  database: dactfsmgpbtmge
  username: tsowomyqcjnhqg
  password:  tu61zm6Q-e_ZOVS7kQ7ZsM5m4W

production:
  adapter: postgresql
  encoding: unicode
  host: ec2-50-16-229-91.compute-1.amazonaws.com
  pool: 5
  database: dactfsmgpbtmge
  username: tsowomyqcjnhqg
  password:  tu61zm6Q-e_ZOVS7kQ7ZsM5m4W
